### ISSUE TITLE
Continuous crash is happened.

### ISSUE THREAD

**Issue by Koichi-Hatake** [Koichi-Hatake/DeepLearningAndroid#2]
Continuous crash is happened when this app invoke again after home screen and touch drawing area.

**Comment by Koichi-Hatake** [comment]
This is Logcat messages.

    java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@8468008
        at android.graphics.BaseCanvas.throwIfCannotDraw(BaseCanvas.java:62)
        at android.graphics.BaseCanvas.drawBitmap(BaseCanvas.java:109)
        at android.graphics.Canvas.drawBitmap(Canvas.java:1456)
        at net.seeeno.deeplearning.SurfaceView.drawLine(SurfaceView.java:179)
        at net.seeeno.deeplearning.SurfaceView.onTouchMove(SurfaceView.java:167)
        at net.seeeno.deeplearning.SurfaceView.onTouchEvent(SurfaceView.java:149)
        at android.view.View.dispatchTouchEvent(View.java:12529)

**Comment by Koichi-Hatake** [comment]
This issue was fixed by 71f2c7d6469734b73d7aa1bd18d15c096fd2c715.
